### ISSUE TITLE
Configure warnings

### ISSUE THREAD

**Issue by piefel** [vtst/ow#111]
This issue strikes a similar vein as #85 and #96 – it would be helpful to configue warnings and errors. Presently, the plugin reports warnings for issues that cannot be corrected, which may hide real issues.

For example: To create a linear gradient for every browser, you have to accomodate for different syntaxes. This means that you will have multiple background-definitions within a single rule. This triggers a warning “The property 'background' is already defined in this block.” – actually 5 of them (because we need 6 such properties). I wish to ignore these warnings somehow.

**Comment by vtst** [comment]
That's a good idea. I'll try to implement something.

**Comment by vtst** [comment]
This is implemented in the codebase, and will be available in the next release.

**Comment by SomMeri** [comment]
@vtst Hi, thank you for all the work you have done with this eclipse plugin, it looks very promising. 

Do you already know when are you going to release the next version? I'm asking because I have a project with huge number of less files and syntax highlighting from this plugin is simply great. The problem is that the plugin reports more then 11365 errors and 1849 warnings on my files. Some of these are legitimate, but most center around not yet implemented things (such as css3 namespaces). 

Ability to turn them off would be greatly appreciated :).

**Comment by vtst** [comment]
I'll try to make a release this week-end.

**Comment by vtst** [comment]
Please note however it will probably not solve all your issues (syntax errors due to unsupported features would still be reported by the plugin). I've seen your bug reports, I'll try to address them too.

**Comment by SomMeri** [comment]
Ah, right - only warnings. Would it be too difficult to make error markers optional too?

I'm porting less.js compiler into java (https://github.com/SomMeri/less4j) and have a lot of test files with all kinds of edge cases only few people use and what not. Some of them even contain intentionally bad less, because I wanted to test what it does on faulty input.

If I could turn off errors, that would solve all 11000 of them at once. I submitted issues only for those I through other people might need too. I can not really tell how many of them will disappear after you fix them and I basically gave up after trying to make sense of so many errors. I also did not wanted to clutter your issue database with tons of requests on rarely used less/css features.

Which also means that you probably do not have to hurry trying to fix my issues, only if you thing that they would add value to other people too.
