### ISSUE TITLE
PDE junit tests -> build with acceptance tests

### ISSUE THREAD

**Issue by bytesandwich** [vtst/ow#140]
eclipse is suggesting to me to [run junit plugin tests](http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Flaunchers%2Fjunit_launcher.htm)

A brief google search turns up [a possible test configuration](http://stackoverflow.com/questions/255370/automating-unit-tests-junit-for-eclipse-plugin-development)

I think tests would give the project a breath of fresh air towards a vigorous future.

**Comment by bytesandwich** [comment]
I'm looking at [groovy-eclipse](https://github.com/groovy/groovy-eclipse) : /org.eclipse.jdt.groovy.core.tests.builder/src/org/eclipse/jdt/core/groovy/tests/builder/BasicGroovyBuildTests.java 

I think that's a pretty good starting point to work from.

**Comment by FagnerMartinsBrack** [comment]
So the plugin does not have test right now, right?
I never developed an eclipse plugin but I have a suggestion that may work (or not, cause no research has been made on it).

In order to avoid regression, mainly for syntax issues, you should create a test project with a bunch of less files splitted into a structured system. It may hold regular tests for complicated treatments and issue specific ones.
Such project could be pushed to the git repo, then developers may create failing cases without having to go deep into the development for one or two issues.

Example:
TestProject/issues/44.less
TestProject/issues/45.less
TestProject/issues/45.less
TestProject/tests/syntax-x.less
TestProject/tests/feature-y.less

I am not sure if the deployment is fast enough to allow running all tests for each small modification, but at least it could help to avoid regression for each release without messing with junit, mockito, etc.

@vtst 
Is this possible?
This is the only eclipse less plugin out there, but fails a lot for the most important project in the web, [Twitter Bootstrap](http://getbootstrap.com/).

**Comment by paulvi** [comment]
@jackphel @FagnerMartinsBrack Would you write test case for framework of your interest?

Having coverage test to catch regressions like #188 make sense, when CI is present #206

**Comment by FagnerMartinsBrack** [comment]
I would have done that at the time I posted this (or at least helped to do so). Right now it is not feasible due to the fact I am drowned in 2 projects.

I am not sure if this issue was closed because it will not be done or because it will be done, another issue requesting documentation for contributing was closed too, so I suppose the author is not willing to implement this.

**Comment by paulvi** [comment]
Yep, the author is [yet] not social enough for such great open-source undertaking.
