### ISSUE TITLE
Less: Allow configurations to be added to the VCs per project

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [vtst/ow#141]
It is very useful.
As it stands I need to mess with the configuration each time I import a new project with egit (Git for Eclipse)
If serializing is not currently possible at least allow setting global eclipse configurations instead of a per project basis.

**Comment by vtst** [comment]
Sorry, but I do not understand exactly what you mean.
Is this for the LESS plugin or for another plugin? What do you mean by VC?
Normally, the project options should be stored in the ${project dir}/.project, so you can add this to your git repository.

**Comment by FagnerMartinsBrack** [comment]
VCS is Version Control System such as git. Currently it does not save in the .project file the configurations I made for the validators (such as disable star hack, imports, etc)

**Comment by vtst** [comment]
Ok, I see. This would require storing them in a project scope, instead of using project persistent properties as the current implementation does. I guess there are some users that will prefer the former option (because it does not pollute their project directory with Eclipse-specific files), and some users that will prefer the latter (because it makes sharing of configuration easier).

http://stackoverflow.com/questions/3525213/eclipse-storing-info-in-project-file

**Comment by FagnerMartinsBrack** [comment]
> I guess there are some users that will prefer the former option (because it does not pollute their project directory with Eclipse-specific files)

A project shared amongst developers should be consistent regarding validation exceptions, so the users that says the settings of a project should be in their machine have no idea of what they are talking about.

If such feature is out of question at least allows to store in the eclipse configurations rather than in the project. When I remove the project from the IDE and add it again I should create all the configurations again, it is annoying. Such thing does not happen with the default Eclipse validators.

**Comment by vtst** [comment]
I implemented workspace preferences.
