### ISSUE TITLE
JS: Pin-Pointing folders. Big projects...

### ISSUE THREAD

**Issue by firecow** [vtst/ow#34]
I just wanna let you know, that I find your Closure plugin very intriguing.

I'm a Game Developer, and the company i work for have just started moving into the HTML5 field, using Google Closure.
All programmers in the company comes from a Java background and a lot of them are used to Eclipse, so we have a great interest in getting this plugin up and running... And i think some of the guys here at the office, knows a little about writing Eclipse plugins. 

However here is my problem using the closure plugin combined with one of my big JS-Projects (621 files).
I simply run out of Heap space, and sometimes i get the Magic Exception.

Here is what i have done:

Used the custompath, pointing at my /src folder. 
But the plugin still seems to be searching all project folders for JS files. And i have a few lying around, for spritemapping, and other js mapping files, that i don't want the plugin to take notice of.

Is there a way to pin-point a specific folder within the my project, for the plugin to search?

**Comment by vtst** [comment]
Hi,

Thanks for the interest in the plugin, and your feedback.
In fact, there are two parts in your bug report:
1. You should never see a MagicException. The plugin should have shown the right exception. I'll try to fix this.
2. You're running out of heap space. Are you sure this is out of heap space or out of stack space? For the stack space, there is a specific comment about it in the source code of the Closure Compiler:
    // Under JRE 1.6, the jscompiler overflows the stack when running on some
    // large or complex js code. Here we start a new thread with a larger
    // stack in order to let the compiler do its thing, without having to
    // increase the stack size for _every_ thread (which is what -Xss does).
    // Might want to add thread pool support for clients that compile a lot.

In the Eclipse plugin, I disabled the creation of the new thread, because it would affect performances. I may add an option to force the creation of this thread.

An another way to address the issue would be to start Eclipse with a larger stack size. You can do this by adding the command-line option -vmargs -Xss256M -Xmx256M (ss is the stack size, mx is the heap size, you may try different value). Could you please try this?

By the way, I'd be interesting to know how the plugin behaves with such a large project, because I did not test it with so large ones. If there are some performance issues, it might be necessary to know a little bit about its structure to see how to optimize things.

## 

Vincent

**Comment by firecow** [comment]
It could very well be that it is the stack running out instead of heap space. I can see that i only have 40mb stack size.
I'll have a play with it monday...

I'll post you some more informations about our JS project there as well.. (Line of code, etc. etc..)

**Comment by firecow** [comment]
Hey, just setup my eclipse with -Xms512m and -Xmx512m...
Ran your plugin on a project with 165 Google Closure documented files containing only 13913 lines of code..  

Got the following two exceptions...

Errors occurred during the build.
 Errors running builder 'Closure JavaScript Builder' on project 'TestProject'.
 net.vtst.ow.closure.compiler.magic.MagicException

Unhandled event loop exception 
 GC overhead limit exceeded

Any idea what this can be ? Is it because the project is too big ?

Ps: 
In eclipse i'm getting this error, out of my goog.inherits

Multiple markers at this line
    - variable goog is undeclared
    - Property inherits never defined on  goog

Which could indicate that i've setup the plugin in a wrong way...
My closure base directory is checked out from googles svn repo, in a folder I've called "/home/firecow/workspace/closure-library/trunk/closure/goog"

**Comment by vtst** [comment]
For the next version, I implemented some feature allowing to select JS files in projects which shall be handled by the closure compiler (see issue #44). This may help to address your problem.

**Comment by firecow** [comment]
Sweet....
I'll test that version out then...
