### ISSUE TITLE
JS: OW doesn’t respect/overrides Include Path

### ISSUE THREAD

**Issue by deno** [vtst/ow#44]
In Project Properties → JavaScript → Include Path:

 1) Enabling closure support overrides include path to project folder.

 2) Once enabled, if user modified the include path, it’s back to project folder immediately after.

**Comment by vtst** [comment]
Thanks for the feedback.
I improved the plugin so that it considers the source files specified in Proeprties > JavaScript > Include Path > Source. This will be available in the next version. The inclusion of external libraries and externs can be specified on the page "JavaScript > Closure > Includes". The inclusion of other projects can be specified on the page "Project References".
I hope all this will fit your needs.

**Comment by vtst** [comment]
Version 0.2.2 released!
