### ISSUE TITLE
Soy: wrong errormark on soydoc

### ISSUE THREAD

**Issue by tharban** [vtst/ow#6]
Hello,

the following (minified) code produces error signs for the following lines:
- first /*\* soydoc: message: no viable alternative at input '/**'
- @param locales: unused parameter, although it gets used (this could be related to the next one)
- first <content tag: mismatched input 'tag' expected {/template}: this is not the end of the template

``` xml
{namespace abc.def}

/**
* @depends template=abc.def.showAsTable
*/

/**
* @param locales a list of strings which gets fetched from the distinct values of the profile field Country (configurable).
*/
{template .config}
<html>
    <head>
        <content tag="pagetitle">Configuration for the displayed stories</content>

          {foreach $locale in $locales}
                <option>{$locale}</option>
          {/foreach}
    </head>
{/template}
```

**Comment by vtst** [comment]
Thanks for the bug report! All issues will be fixed in the next version. 

More details:
1. /*\* soydoc: message: no viable alternative at input '/**': Soy doc which were not attached to template were not allowed, while they are accepted by the template compiler. Fixed.
2. @Param locales: unused parameter, although it gets used (this could be related to the next one) : This is just a consequence of 3.
3. first <content tag: mismatched input 'tag' expected {/template}: this is not the end of the template : The keyword "tag" was specially handled in the parser. There was no reason for that. Fixed.
