### ISSUE TITLE
JS: OW silently dies when circular dependencies are present

### ISSUE THREAD

**Issue by deno** [vtst/ow#71]
If circular dependencies are present OW shows no completion proposals without producing any errors. 
E.g. closure compiler shows an error like this:

```
/foo.js: ERROR - Circular dependency in the chain [foo.js, bar.js] -> foo.js
```

OW doesn’t and all files affected are silently ignored. 

Example foo.js:

``` javascript

goog.provide('xyz.Foo')

goog.require('xyz.Bar')

xyz.Foo = {…}

```

Example bar.js:

``` javascript

goog.provide('xyz.Bar')

goog.require('xyz.Foo')

xyz.Bar = {…}
```

**Comment by firecow** [comment]
Oh, yeah.. I've noticed this as well... 
I actually think, thats why some of my big projects doesn't build.
It would be nice to be told, that i've fucked up :D

**Comment by vtst** [comment]
Thanks for the bug report. I fixed the code so that an error is reported at the level of the project (you will see the error marker on the project icon, and you will see the error message in the Problem view). Unfortunately, the error does not point directly to the source code line where the error occurs, because this would be much more complicated to do (the Closure compiler does not give the information in a directly usable form).
