### ISSUE TITLE
Cannot install LESS and Closure Templates plugin in new version of Eclipse

### ISSUE THREAD

**Issue by gatapia** [vtst/ow#75]
On the new version of Eclipse (I've tried Java and EE edition) the LESS and Closure Templates plugin cannot be installed.  Note:  The Ow plugin installs fine.

Version info of Eclipse:
Eclipse Java EE IDE for Web Developers.

Version: Juno Release
Build id: 20120614-1722

Error Details:
Cannot complete the install because one or more required items could not be found.
  Software being installed: LESS 1.0.9 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.9)
  Missing requirement: net.vtst.ow.eclipse.less 1.0.9 (net.vtst.ow.eclipse.less 1.0.9) requires 'package org.eclipse.xtext.xtend2.lib 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: LESS 1.0.9 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.9)
    To: net.vtst.ow.eclipse.less [1.0.9]

Tnx

**Comment by mchiocca** [comment]
Hi. Installing Xtext/Xtend2 is a prerequisite to installing these plugins. Have you installed these as per the instructions given at http://www.normalesup.org/~simonet/soft/ow/eclipse-less.en.html before attempting to install the plugins?

**Comment by vtst** [comment]
Thanks for the bug report. The problem comes from the fact that Xtend was shipped with Xtext in the past, while it is now distributed manually. So the dependency problem did not appear in the past. As a workaround, you should try to install Xtend before the plugins (it should be available from Juno release site).
The problem is normally already fixed in the code base. I'll make a release shortly.

**Comment by gatapia** [comment]
Thanks for the new link.

Perhaps put this in the [closure library plugin page](http://www.normalesup.org/~simonet/soft/ow/eclipse-closure-javascript.en.html). As they are the exact steps I following when installing.

Thanks all

**Comment by vtst** [comment]
The unexpected dependency is normally removed in the latest version.
