### ISSUE TITLE
Less: Problems with twitter/bootstrap

### ISSUE THREAD

**Issue by opensource21** [vtst/ow#85]
I'm playing around with bootstrap and started to look at less-compilers. Found you interesting plugin. However there are 2 problems:
1. bootstrap.less imports many files. Each file alone can't compile because they doesn't import `variables.less`and
   `bootstrap/mixins.less`. So I get tons of errors. This makes this useless. 
2. There exist a tricky solution for [variable arguments](http://www.toekneestuck.com/blog/2012/05/15/less-css-arguments-variable/). This is use from bootstrap. Again the plugin fails.

Unfortunately I have no idea how to fix this with xtext. Any suggestions are welcome.

**Comment by marcospassos** [comment]
I have the same issue.

**Comment by marsmining** [comment]
Same here.

**Comment by vleerpluisje** [comment]
Anyone already know how to solve this? Plugin is pretty useless now :(

**Comment by FagnerMartinsBrack** [comment]
This is quite an important issue at the moment. I have the same issue when using bootstrap as a base for a custom css project.

The plugin should be able to allow custom configuration of errors and warnings because one could be using less files in another context. In my case I use grunt for building.

The current workaround is to implicitly declare import in the non relevant files (what cannot be done in your case since you are probably using bootstrap without modifying its source).

Example (buttons.less):

```
@import "variables.less";
```

**Comment by DaSchTour** [comment]
I have the same problem, it's really sad, that this plugin can't hand over mixins. This would be a really great plugin if this would work correctly.

**Comment by vtst** [comment]
FYI, I'm currently working on this. Is is pretty complicated, hence it takes time, but many of the commit in the last month in the project are related to this.

**Comment by vtst** [comment]
This is the same as #147.
