### ISSUE TITLE
eclipse install problem

### ISSUE THREAD

**Issue by bazjapan** [vtst/ow#97]
Thanks for the work on this.
I'm having a problem installing through the update site. I get the following error. Any ideas how I can solve this? thanks.

Cannot complete the install because of a conflicting dependency.
  Software being installed: LESS 1.0.10 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.10)
  Software currently installed: Adobe Flash Builder 4.0.0 (com.adobe.flexbuilder.standalone.product 4.0.0)
  Only one of the following can be installed at once: 
    OSGi System Bundle 3.7.0.v20110613 (org.eclipse.osgi 3.7.0.v20110613)
    OSGi System Bundle 3.4.3.R34x_v20081215-1030 (org.eclipse.osgi 3.4.3.R34x_v20081215-1030)
    OSGi System Bundle 3.7.1.R37x_v20110808-1106 (org.eclipse.osgi 3.7.1.R37x_v20110808-1106)
    OSGi System Bundle 3.5.1.R35x_v20090827 (org.eclipse.osgi 3.5.1.R35x_v20090827)
    OSGi System Bundle 3.7.2.v20120110-1415 (org.eclipse.osgi 3.7.2.v20120110-1415)
  Cannot satisfy dependency:
    From: Adobe Flash Builder 4.0.0 (com.adobe.flexbuilder.standalone.product 4.0.0)
    To: org.eclipse.rcp.feature.group [3.5.1.R35x_v20090811-9SA0FxVFqE70OL1ARMrfcO6e7BA6]
  Cannot satisfy dependency:
    From: net.vtst.ow.eclipse.less 1.0.10 (net.vtst.ow.eclipse.less 1.0.10)
    To: package org.osgi.framework 1.6.0
  Cannot satisfy dependency:
    From: LESS 1.0.10 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.10)
    To: net.vtst.ow.eclipse.less [1.0.10]
  Cannot satisfy dependency:
    From: Eclipse RCP 3.5.1.R35x_v20090811-9SA0FxVFqE70OL1ARMrfcO6e7BA6 (org.eclipse.rcp.feature.group 3.5.1.R35x_v20090811-9SA0FxVFqE70OL1ARMrfcO6e7BA6)
    To: org.eclipse.osgi [3.5.1.R35x_v20090827]

**Comment by vtst** [comment]
Which version of Eclipse are you using?
Did you try from a clean installation from the last version of the Eclipse platform (the Java EE variant)?

**Comment by alex6o** [comment]
+1 for dependency problems ... based on the latest eclipse (java version) version i installed the pdt extension; installing TMF Xtext worked without problems, but installing LESS ends with the following problem:

Cannot complete the install because of a conflicting dependency.
  Software being installed: LESS 1.0.12 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.12)
  Software currently installed: Xtext Runtime 2.1.1.v201111141332 (org.eclipse.xtext.runtime.feature.group 2.1.1.v201111141332)
  Only one of the following can be installed at once: 
    Xtext 2.0.1.v201108020636 (org.eclipse.xtext 2.0.1.v201108020636)
    Xtext 1.0.2.v201102150722 (org.eclipse.xtext 1.0.2.v201102150722)
    Xtext 2.1.1.v201111141332 (org.eclipse.xtext 2.1.1.v201111141332)
    Xtext 2.3.0.v201206120633 (org.eclipse.xtext 2.3.0.v201206120633)
    Xtext 2.3.1.v201208210947 (org.eclipse.xtext 2.3.1.v201208210947)
    Xtext 2.2.1.v201112130541 (org.eclipse.xtext 2.2.1.v201112130541)
  Cannot satisfy dependency:
    From: net.vtst.ow.eclipse.less 1.0.12 (net.vtst.ow.eclipse.less 1.0.12)
    To: bundle org.eclipse.xtext 2.2.1
  Cannot satisfy dependency:
    From: LESS 1.0.12 (net.vtst.ow.eclipse.less.feature.feature.group 1.0.12)
    To: net.vtst.ow.eclipse.less [1.0.12]
  Cannot satisfy dependency:
    From: Xtext Runtime 2.1.1.v201111141332 (org.eclipse.xtext.runtime.feature.group 2.1.1.v201111141332)
    To: org.eclipse.xtext [2.1.1.v201111141332]

any ideas how to fix this problem? 

Eclipse IDE for Java Developers
Version: Juno Service Release 1
Build id: 20120920-0800

**Comment by vtst** [comment]
It seems you have Xtext 2.1.1 installed, 2.2.1 at least is required.
You should try to update Xtext manually from Eclipse update manager.

**Comment by derekcicerone-zz** [comment]
I just made the same mistake.  You may want to update the instructions.  They ask for "TMF XText" to be installed but its seems to only be called "XText" now.
